server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud-detection-service-DB
    username: postgres
    password: max228488
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: paymentCreatedEventConsumer
    stream:
      bindings:
        paymentCreatedEventConsumer-in-0:
          destination: payments-created
          group: fraud-detection-service
          content-type: application/json

        paymentRiskResult-out-0:
          destination: payments-risk-assessed
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/