server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment-service-DB
    username: postgres
    password: max228488
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: paymentRiskResultConsumer
    stream:
      bindings:
        paymentCreated-out-0:
          destination: payments-created
          content-type: application/json

        paymentCompleted-out-0:
          destination: payments-completed
          content-type: application/json

        paymentFlagged-out-0:
          destination: payments-flagged
          content-type: application/json

        paymentBlocked-out-0:
          destination: payments-blocked
          content-type: application/json

        paymentRiskResultConsumer-in-0:
          destination: payments-risk-assessed
          group: payment-service
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: basic

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/