server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-DB
    username: postgres
    password: max228488
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: userRegisteredConsumer
    stream:
      bindings:
        userRegisteredConsumer-in-0:
          destination: user-events
          group: user-service
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/